repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            "add",
            "ci",
            "docs",
            "feat",
            "fix",
            "bug",
            "refactor",
            "revert",
            "test",
            "security",
            "perf",
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: fix-byte-order-marker
      - id: forbid-new-submodules

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.9
    hooks:
      - id: pylint
        args: ["--rcfile=pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
        exclude: "tests"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "^tests/"
        args:
          - "-r"

  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
          [
            "--dev",
            "--format",
            "requirements.txt",
            "--output",
            "requirements.txt",
          ]
