name: BuildDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install poetry==1.2.2
      - run: poetry install
      - run: poetry run mkdocs gh-deploy --force --clean --verbose
