name: BuildDocs

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(main)') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version 1.3.1
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          rm install-poetry.py
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - run: poetry env use python3.10
      - run: poetry install --with docs
      - run: poetry run mkdocs gh-deploy --force --clean --verbose
