name: Testing

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version 1.3.1
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          rm install-poetry.py
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies and project
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install
      - name: Check with isort
        run: |
          poetry run isort --check-only .
      - name: Check with black
        run: |
          poetry run black --check ./src/autoembedder
      - name: Check with mypy
        run: |
          poetry run mypy --config-file=pyproject.toml .
      - name: Lint with pylint
        run: |
          poetry run pylint --rcfile=pyproject.toml ./src/autoembedder
